runtime: php
env: flex
runtime_config:
  document_root: public
  operating_system: "ubuntu18"
  runtime_version: "7.4"
# for detecting static files in the public folder
skip_files:
    - .env
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100
env_variables:
  APP_DEBUG: true
  APP_ENV: production
  APP_NAME: "GCP App - CODE"
  LOG_LEVEL: debug
  APP_KEY: base64:Uf8l/ytW7f0+/6od3gSCIenKzh1UPzLAML/S36FYtPQ=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  BACKBLAZE_ACCESS_KEY_ID: 00063daf79f81920000000003
  BACKBLAZE_SECRET_ACCESS_KEY: K000kvrhAKaeb6WkP4RsoQlNjgOxlXI
  BACKBLAZE_DEFAULT_REGION: us-west-0
  BACKBLAZE_BUCKET: asset-control
  BACKBLAZE_URL: https://f000.backblazeb2.com/file/asset-control
  BACKBLAZE_ENDPOINT: https://s3.us-west-000.backblazeb2.com
  RECAPTCHA_SECRET: 6LeKd-4cAAAAADzibP6cAwBfdJYuZ7kg5d0Ypkig
  MAX_UPLOAD_DOCUMENT_SIZE: 30
  ASSET_STORAGE_DISK: backblaze
  ASSET_STORAGE_URL: https://f000.backblazeb2.com/file/asset-control
  # DB_CONNECTION: mysql
  # DB_HOST: aws.connect.psdb.cloud
  # DB_PORT: 3306
  DB_DATABASE: assets
  DB_USERNAME: root
  DB_PASSWORD: admin123
  DB_SOCKET: '/cloudsql/ivory-analyst-295912:asia-southeast1:assets'
  # MYSQL_ATTR_SSL_CA: '/etc/ssl/certs/ca-certificates.crt'
  APP_URL: "https://ivory-analyst-295912.as.r.appspot.com/"
  ASSET_URL: ""
  SESSION_DRIVER: cookie
  QUEUE_CONNECTION: sync
  MAIL_MAILER: smtp
  MAIL_HOST: ""
  MAIL_PORT: 465
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: ssl
  MAIL_FROM_ADDRESS:
  MAIL_FROM_NAME: "Google cloud vision"
  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_APP_CLUSTER: mt1
# the tmp folder is used for caching on GCP as opposed to the default storage folder
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php
  PASSPORT_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCLc2TYmtI0Jymf
    xFupcqYlSVx5LedaVR7jXbX8hC19HZQtRTjOos7/eHF3PGL2dnEw9+4rJxeHU1gq
    W0Jtp1gHmGQsWJ2wInttNStZEUcaU4YMzlhK+tNxf6XShZjKxkFsS4K8e7Xsqe3j
    P7vNxJ3sU12ZZKFfR7Yiag311ZJJuA5i3b6J2Gg/zdsIi/W7Wh93Rkv5oGGQqtUu
    Zns+G6nxOku6r+CX77n23F3NNPB0z3xjGHikjcBTHUpY3oxEAtui1zxTyf2Bl6w2
    eqS68Q2oaJTJA/JLgS6brllz4Iyh8QHri0cIS6D0NIDmZiLthTOwZFLvLtoAtd4p
    njBSv3tPXxMN5wwuw0DLt1kembx+9z3SCZObs7lGPVKMxmW/MwVJ723mBU363Ubp
    +E2PgNQa8KYxEJfgUA7cgCZLpGLCf/w7n0Az76Kyb2NVqWg4jCHHo2iQ6jL4BHbd
    QeFQGWk4TSq3entloPLDiCHGAtcYiGBFAXtuvhkqn6dVxebUui5mJCxceZA9eCMM
    bL4DBU+wmv5Dcv3oMqz/6Xj+vfFi0NVFN0Zus9HxnHX6AlG39h8j2rl5uWYewDEx
    +O/RZz6J43VBaa9YYQKX1idLuiqgPFPOPobZ2P2UMBXiqA1yBWjiwjNb8/nzk8pk
    jUUmiJfIK+puAO11VUFcNrCKALuyvQIDAQABAoICABfySuD/RRV7nCQ5XdwtOeax
    QFX20gGrGFDG6NdiA0W27JkRh/3D63PnROTK09uq3ykfiiCS5/FvGHa9kRyvXeh/
    /MO4u+thIHzSYo068FDPAvfz/ylxBRo6Z0lNc71uahGkreCcBdOMIrOhYCinmM7a
    SfprU2K/N8GVIKyUbjiGiMHlfjDBnrVGLlS7ZAk2Iq0ivy0wo1BqZY1AP+2cZoRs
    FFEMnq64leCUWu9AJgKJFr0VmLH5PYuIPhogrUmIjBrchxmEWCoG16XLTbpkZooC
    23nhWZwppM1LFUVWzA+LCV9fXWVJR2xoD7KA24KaGxQxRiSYkQsKMApJhdbP1ua7
    ZYZkPNYSnIl/gsQN6Kj8sJwgYb5cpJchv4E0Fj6qUBOJqZsws/1KTfFKC3qgWjq/
    FD5gmITY+29Sipsms3s+J9Mwwdm58KybXwDmRuIWxEXbrJjusJMmAr3SCrpxzB7V
    hjYAXUOnKDVAcKqWg7t7u4y2UeBlmbgwJ30e2JHI1jHY4UNuEbWP/MN/jtE+f/TS
    tNcjJ8KxZ/iL46HWIxByBeE4F0FJoERjxDCkRRdkdv/55PX/WSOCAc8/y/arK8GK
    kFt+BIOsuse/czOKq5m89Jo+g29C38q6nLpZzewBfZgB2xS34n3DTbI6f7T5O3yt
    KhV0z4jnJlEhQve0sXmpAoIBAQC1ln9Vc7o5ruV2mbzJXsH8KBlo8mMVyyMUkjdy
    8e708RqQtic2Mp7dLThHHWP/XTsqL4FiADXZbETYbJLnQ/f1uCbKMip3qCl00Se7
    tjB/3uctWJfYUlFnAC2hLA+ye9ZjXPECwYyvuWP2CJxJ4HPcWT0z/R+SEzBCaNr7
    RPx34NDwNYhZaInCGg7u7n6VvI5SAFWZrY9wcWCnDaLhm5cXxlhLz6rexLsCnnV4
    azXP4Gwjq2+/9gxNvnFuFirRd7/0YQONi2MYWyyZPMg0+WAQ90gjfLf5DuW7xWZe
    jfcVRiMNQ5W/qvhI3PipYzgI+OrvQ2iuo4pg3GUFanMYyTlzAoIBAQDEmH7g3YJt
    B92ETTMe628+p2xDr8M7Lz7nRQU3/Grpn5W9UjoMOai+YKzqW5oy4AiN77cUHeN6
    3BdQg2hdbhcSIpEFKi/2TxkDxRUDfhFh392YoNCkHAaBTgR1P3RBG66UkWoN6+Q3
    JyqCRJZWagS5VX/GnDqHdyyX8Jvb1hqmTShmcDO5w/xISz4WQchIySbdcxUFJopS
    WIMxN91j2BR9c9m4ue38ajRe9U7A0aJHZuEvo/4jfqgNyJKOU2J0DhvRSD23BDWt
    JFZOF3CwNGFp3RxZmjhL9XgfzBLFsWR6FeKdKduzk2n8jU0hkzzGIJKE+NogW7Z7
    wnOKKy4SGBcPAoIBAEQCLoRxiGCMOVJ297avb5Wh6wpcJXIHF4dfz7aUF7vTBPEH
    1527zbXmdrpjroz4fO0qx5lNnN1maE5qM4a79QUpSBXYPgF8kLI4l1n9PSLW99wK
    3yvcgLJD5dMELojZSo0CRR2UIb26gE6oIOimUJ5JKdvrxEQwPZXRsZoD106Ke5ZL
    ZlqeBWIV4lvoJK6t5NufVm/tCdjCDcHjIIrAfBEibvVNvKAcLDIp6LMF7CyDz9x4
    G61YWHlRhygE01qKL/E12F/NwXpgw05M7mqwryMLihAIaNq1kqMFpnZpUw27q+sO
    0enr/XtEjzjZeSYbG9oqc+1cQLpQMOGbYan5yzMCggEBALFOo+fkf7QcCuI+yiNR
    zWQhlZg6Vgbz5nSooDtNMZOA9YjpNyc9fX4uLOW1Ng46VhzFHUZMapStGW3pBmB1
    YONfP5H76YPo9LOctQYQVlcCk5YLPAE2sXs/RPAGCbCK6dpeh9sEbDB9523TtA89
    0QLiJLqYvoTcq+BhBgCwShrArfYtrckWBFujWNyz+ZIDsUS6fTPG/auk3rWuH8Lj
    6B75NFzRe91SX+dgsOVgbE6fb+sKqbOTkLfVtLAebkYjT11iHR8J8es1QY1uwJh6
    tXzICcCaQbnoKq3q3OdlxSwCvv5l+RstkcJQIkdsxrweNmctFXVnod5ektwDc6qo
    BWsCggEAUgf34K1QygvQi1Q9EN1rfa0TuHiyKe/lu6gaYqcQYIn/T1qDoOeZmWZa
    Rr4Q3ydbhPdoCRCnfYxeBMiZbePOdLqRGlthamPxlChtp0J+SfpRr9yQbYb9pQs5
    CMNZr2DxHolI6f5d/sTfZBZ5UG7piCjZ122Pm3A47QsBrXkWamPpzJ7oCC+JX6x8
    GWApoKd7WAyL5AHmrXMHmbxEe5ERnYDYWlbg3d7wv94QQ13ezYOkkro7k8zCaaAK
    GobDkhT7YMCaWmkOZFUXmkHJ4B1EGsL7HoacXHxFBXnCrf+eXZZXokm2SD6TF5ci
    tLSO292kP0VTdz/LM7nGWRNoLt4Bxg==
    -----END PRIVATE KEY-----
  PASSPORT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAphYClNVNMxKA7GFC5jSc
    moHQCyzhwe57WBj0DAgef2FqgN2n0OSTG6jRNVLfRUPIQlh8nqWYURrF2M43ltuo
    FcDbbsHX/hFrs5+Fc67Dd/BLl+pfgLg3tvA24RHrp4zOLP0CDtZCMWnr5GgiIv2k
    84mEueagtTHce8FjXxPLnvmnoy0jg9tBxXTKc+YrxjH/3Fd8MQNJNzRh6I6WCzX2
    XTO0zMVKVLslcv75THOc6diOF9xxFSuVyuLYNL31Pkh/g0ThM2AV2TEuqkGLdCKy
    uQAkI9lCU70RcNCwp+iayIux8LNQ2NAWl+wwU9eYTwVdthS1msbSJ6TaFWCvqjHB
    J3HlDmnzPgGbhbawgQ7fV7qi1zRJxBDWabZ8NXvkNhDUyid3atjXfkvKTxsjOzdF
    S8NDJH7EEr4anvSsY8Yb9RKbYd1X0u8Wiez3Iyq80ythrQOnit/IsRe+1ZZu7Y0J
    frXEbnRljoUq0gJy3AfbKK97/zxJp1tCKOnTW7EVDmf55C1Cadnfr/0Wk7T6sGAJ
    mjm901q6ariKzrWuYHV/bXezTfCGYDgTlMWXxOxoWiLi3BBrslk9kuKKsm/h/pE3
    3Hk0nuNL6/TQrW6lkx8jSFgejM4TQpf6xJ4PSAK5papkanIfUMr10b6S3SlcZivH
    N0UAXoxaBXonmzTQfTjjTMcCAwEAAQ==
    -----END PUBLIC KEY-----

beta_settings:
  cloud_sql_instances: 'ivory-analyst-295912:asia-southeast1:assets'
